config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  devise_scope :user do
  # Conditional root route based on user authentication status
  authenticated :user do
    root 'categories#index', as: :authenticated_root
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  unauthenticated do
    root 'splash#index', as: :unauthenticated_root
  end
end
  get 'splash/index'

  resources :categories, only: [:index, :new, :create] do
    resources :transactions, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :icon, presence: true
  belongs_to :user, inverse_of: :categories
  has_many :transactions, dependent: :destroy

  def self.unique_name(name, icon, user_id)
    find_by(name:, icon:, user_id:) || new(name:, icon:, user_id:)
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  validates :name, :amount, presence: true
  belongs_to :category

  def self.create_with_unique_category(name, amount, category_name)
    category = Category.unique_name(category_name)
    create(name:, amount:, category:)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_one_attached :profile_pic # Active Storage
  has_many :categories, dependent: :destroy # Ensure categories are deleted with user
  has_many :transactions, dependent: :destroy # Ensure transactions are deleted with user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_up_path_for(_resource)
    new_user_session_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password profile_pic])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[name email password current_password profile_pic])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  include CategoriesHelper

  def index
    @categories = current_user.categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  private

  def category_total_amount(category)
    category.transactions.sum(:amount)
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category

  def index
    @transactions = @category.transactions.order(created_at: :desc)
    @total_amount = @transactions.sum(:amount)
  end

  def new
    @transaction = @category.transactions.new
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user_id = current_user.id

    if @transaction.save
      redirect_to category_transactions_path(@transaction.category), notice: 'Transaction was successfully created.'
    else
      render :new
    end
  end

  private

  def set_category
    @category = current_user.categories.find(params[:category_id])
    logger.debug "Category: #{@category}"
  end

  def transaction_params
    params.require(:transaction).permit(:name, :amount, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
# app/helpers/categories_helper.rb

module CategoriesHelper
  def category_total_amount(category)
    category.transactions.sum(:amount)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/categories/_form.html.erb
<%= stylesheet_link_tag 'newforms', media: 'all' %>

<nav class="navbar">
<a href="<%= categories_path %>" class="back-button">
  <%= image_tag('arrow-left.svg', alt: 'Back', style: 'cursor: pointer; width:22px; filter: invert(1);') %>
</a>
  <h1>Add New Category</h1>
</nav>
<div class="container">
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.select :icon, options_for_select(Dir.glob('app/assets/images/icon/*.png').map { |path| [File.basename(path, '.*').capitalize, File.basename(path)] }) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</div>

app/views/categories/index.html.erb
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
  .category-title {
    font-size: 1.5rem;
    font-weight: bold;
    margin-bottom: 1rem;
  }

  .category-card {
    display: flex;
    background-color: #ffffff;
    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
    border-radius: 0.5rem;
    padding: 1rem;
    margin-top: 1rem;
    flex-direction: row;
    justify-content: space-between;
    align-items: center;
  }

  .category-name {
    font-size: 1rem;
    font-weight: bold;
    color: #3182ce;
    text-decoration: none;
  }

  .category-name:hover {
    text-decoration: underline;
  }

  .category-description {
    font-size: 0.875rem;
    margin-top: 0.5rem;
  }

  .category-total-amount {
    font-size: 1rem;
    font-weight: bold;
  }

  .add-category-button {
    position: fixed;
    bottom: 0;
    left: 0;
    width: 100%;
    display: flex;
    justify-content: center;
    padding: 1rem 0;
    background-color: #5fb523;
    color: #ffffff;
    font-weight: bold;
    text-decoration: none;
  }

  .add-category-button:hover {
    background-color: #2c5282;
  }

  .navbar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1rem;
    background-color: #3182ce;
    color: #ffffff;
  }

  .navbar .app-name {
    font-size: 1.5rem;
    font-weight: bold;
  }

  .navbar .sign-out-button {
    background-color: transparent;
    color: white;
    padding: 0.5rem 1rem;
    border-radius: 0.5rem;
    text-decoration: none;
  }

  .navbar .sign-out-button:hover {
    background-color: #2c5282;
    color: #ffffff;
  }
</style>
</head>
<body>
<nav class="navbar">
  <span class="app-name">Budget</span>
  <h1 class="category-title">Categories</h1>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "sign-out-button" %>
</nav>



<% @categories.each do |category| %>
  <div class="category-card">
    <%= image_tag("icon/#{category.icon}", alt: category.name, class: "category-icon", style: "width: 100px; height: 100px;") %>
    <%= link_to category.name, category_transactions_path(category), class: "category-name" %>  <%= category_total_amount(category) %>
  </div>
<% end %>

<a href="<%= new_category_path %>" class="add-category-button">Add a New Category</a>
</body>
</html>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/splash/index.html.erb
<%= stylesheet_link_tag 'splashScreen', media: 'all' %>

<div class="container">
  <div class="card">
    <div class="card-content">
      <h1 class="title">BudgetBuddy</h1>
      <%= link_to "Log In", new_user_session_path, class: "button button-login" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "button button-signup" %>
    </div>
  </div>
</div>

app/views/transactions/index.html.erb
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>

  body {
      font-family: 'Proxima Nova', sans-serif;
    }

    .transaction-title {
      font-size: 1.5rem;
      font-weight: bold;
      margin-bottom: 1rem;
    }

    .transaction-card {
      background-color: #ffffff;
      box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
      border-radius: 0.5rem;
      padding: 1rem;
      margin-top: 1rem;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .transaction-details {
      font-size: 1rem;
    }

    .transaction-name {
      font-weight: bold;
    }

    .transaction-amount {
      color: #5fb523;
    }

    .add-transaction-button {
      position: fixed;
      bottom: 0;
      left: 0;
      width: 100%;
      display: flex;
      justify-content: center;
      padding: 1rem 0;
      background-color: #5fb523;
      color: #ffffff;
      font-weight: bold;
      text-decoration: none;
    }

    .add-transaction-button:hover {
      background-color: #2c5282;
    }

    .navbar {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 1rem;
      background-color: #3182ce;
      color: #ffffff;
    }

    .navbar .transaction-title {
      font-size: 1.5rem;
      font-weight: bold;
      margin: 0;
      text-align: center;
      flex-grow: 1;
    }

    .navbar .back-button {
      background-color: transparent;
      text-decoration: none;
    }

    .navbar .back-button:hover {
      background-color: #2c5282;
      color: #ffffff;

      .transaction-ti {
        display: flex;
        align-items: center;
        margin-bottom: 1rem;
      }


      .transaction-ti h2 {
        font-size: 1.2rem; /* Adjust font size as needed */
        margin: 0; /* Remove default margin */
      }


    }
  </style>
</head>
<body>
  <nav class="navbar">
    <a href="<%= categories_path %>" class="back-button">
      <%= image_tag('arrow-left.svg', alt: 'Back', style: 'cursor: pointer; width:22px; filter: invert(1);') %>
    </a>
    <h1 class="transaction-title">Transaction</h1>
  </nav>

  <div class="transaction-ti">
  <%= image_tag("icon/#{@category.icon}", alt: @category.name, class: "category-ic", style: "width: 100px; height: 100px;") %>
  <h2>Total Amount for <%= @category.name %>: <%= @total_amount %></h2>
</div>




  <% @transactions.each do |transaction| %>
    <div class="transaction-card">
      <div class="transaction-details">
        <span class="transaction-name"><%= transaction.name %></span>
         <span class="transaction-amount"><%= transaction.amount %></span>
      </div>
    </div>
  <% end %>

  <%= link_to "Add a New Transaction", new_category_transaction_path(@category), class: "add-transaction-button" %>
</body>
</html>

app/views/transactions/new.html.erb
<%= stylesheet_link_tag 'newforms', media: 'all' %>
<nav class="navbar">
<a href="<%= categories_path %>" class="back-button">
  <%= image_tag('arrow-left.svg', alt: 'Back', style: 'cursor: pointer; width:22px; filter: invert(1);') %>
</a>
<h1>Add a new transaction</h1>
</nav>

<%= form_with(model: @transaction, url: category_transactions_path(@category)) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>

  <div>
    <%= form.label :amount %>
    <%= form.number_field :amount, required: true %>
  </div>

  <div>
    <%= form.label :category_id, "Category" %>
    <%= form.collection_select(:category_id, current_user.categories, :id, :name, { selected: @category.id }, { class: 'form-control', required: true }) %>
  </div>

  <div>
    <%= form.submit "Save" %>
  </div>
<% end %>